In [1]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [4]:
#if you have dataset use this:
#df = pd.read_csv('covid_toy.csv')

#if you don't have use this
import pandas as pd

url = "https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day28-column-transformer/covid_toy.csv"

df = pd.read_csv(url)

df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [6]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [7]:
#to null values
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [8]:
#1)In Column 'gender' we use OneHotEncoder
#2)In Column 'fever' we use SimpleImputer
#3)In Column 'cough' we use OrdinalEncoder
#4)In Column 'city' we use OneHotEncoder

In [22]:
from sklearn.model_selection import train_test_split

x_train, x_test , y_train, y_test = train_test_split(
    df.drop(columns=['has_covid']),
    df['has_covid'], test_size=0.2)

In [23]:
x_train

    age  gender  fever   cough       city
67   65    Male   99.0    Mild  Bangalore
9    64  Female  101.0    Mild      Delhi
70   68  Female  101.0  Strong      Delhi
83   17  Female  104.0    Mild    Kolkata
23   80  Female   98.0    Mild      Delhi
..  ...     ...    ...     ...        ...
78   11    Male  100.0    Mild  Bangalore
88    5  Female  100.0    Mild    Kolkata
92   82  Female  102.0  Strong    Kolkata
73   34    Male   98.0  Strong    Kolkata
56   71    Male    NaN  Strong    Kolkata

[80 rows x 5 columns]

If You Don't Know , How to use Column Transformer , Use this

In [24]:
#adding simple imputer to fever colunm
from sklearn.impute import SimpleImputer

si = SimpleImputer()

# train data
x_train_fever = si.fit_transform(x_train[['fever']])

# test data (IMPORTANT: only transform, not fit)
x_test_fever = si.transform(x_test[['fever']])

print(x_train_fever.shape)

(80, 1)

In [25]:
x_train_fever

array([[ 99.        ],
       [101.        ],
       [101.        ],
       [104.        ],
       [ 98.        ],
       [100.        ],
       [104.        ],
       [104.        ],
       [100.        ],
       [100.        ],
       [101.        ],
       [103.        ],
       [103.        ],
       [ 99.        ],
       [102.        ],
       [ 99.        ],
       [104.        ],
       [103.        ],
       [ 99.        ],
       [104.        ],
       [104.        ],
       [ 98.        ],
       [100.        ],
       [102.        ],
       [104.        ],
       [103.        ],
       [104.        ],
       [100.        ],
       [ 99.        ],
       [ 98.        ],
       [101.        ],
       [100.        ],
       [102.        ],
       [103.        ],
       [102.        ],
       [100.        ],
       [104.        ],
       [101.        ],
       [103.        ],
       [104.        ],
       [102.        ],
       [100.        ],
       [102.        ],
       [103.        ],
       [101.02739726],
       [101.        ],
       [ 99.        ],
       [ 98.        ],
       [101.02739726],
       [101.        ],
       [101.02739726],
       [104.        ],
       [ 98.        ],
       [104.        ],
       [101.02739726],
       [101.        ],
       [ 99.        ],
       [102.        ],
       [102.        ],
       [101.02739726],
       [101.        ],
       [101.        ],
       [ 98.        ],
       [101.02739726],
       [104.        ],
       [ 98.        ],
       [100.        ],
       [ 98.        ],
       [104.        ],
       [101.        ],
       [ 98.        ],
       [ 98.        ],
       [102.        ],
       [ 98.        ],
       [ 98.        ],
       [100.        ],
       [100.        ],
       [102.        ],
       [ 98.        ],
       [101.02739726]])

In [26]:
#Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong',]])
x_train_cough = oe.fit_transform(x_train[['cough']])

#Also the test Data
x_test_cough = oe.fit_transform(x_test[['cough']])

print(x_train_cough.shape)

(80, 1)

In [27]:
x_train_cough

array([[0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.]])

In [28]:
#OneHotEncoder -> gender , city
oh = OneHotEncoder(drop='first', sparse_output=False)
x_train_gender_city = oh.fit_transform(x_train[['gender', 'city']])

#Also the test Data
x_test_gender_city = oh.transform(x_test[['gender', 'city']])

print(x_train_gender_city.shape)

(80, 4)

In [29]:
#Extracting age
x_train_age = x_train.drop(columns=['gender', 'fever', 'cough', 'city']).values

#Also the test Data
x_test_age = x_test.drop(columns=['gender', 'fever', 'cough', 'city']).values

x_train_age

array([[65],
       [64],
       [68],
       [17],
       [80],
       [19],
       [56],
       [12],
       [27],
       [27],
       [38],
       [60],
       [83],
       [49],
       [20],
       [25],
       [16],
       [16],
       [59],
       [25],
       [75],
       [12],
       [13],
       [49],
       [18],
       [46],
       [44],
       [55],
       [60],
       [31],
       [49],
       [19],
       [24],
       [70],
       [69],
       [11],
       [51],
       [14],
       [73],
       [34],
       [33],
       [27],
       [ 5],
       [48],
       [38],
       [42],
       [22],
       [81],
       [42],
       [19],
       [75],
       [54],
       [83],
       [51],
       [82],
       [34],
       [72],
       [82],
       [74],
       [20],
       [15],
       [ 8],
       [26],
       [34],
       [ 6],
       [64],
       [80],
       [24],
       [42],
       [65],
       [71],
       [ 5],
       [64],
       [65],
       [73],
       [11],
       [ 5],
       [82],
       [34],
       [71]])

In [30]:
print(x_train_gender_city)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 1. 0.]
 [1. 1. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 1. 0.]
 [1. 0. 1. 0.]
 [0. 0. 0. 0.]
 [1. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 1.]
 [1. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [1. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 1. 0.]
 [1. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 1. 0.]
 [1. 0. 1. 0.]]

In [36]:
x_train_transformer = np.concatenate(
    [x_train_age, x_train_fever, x_train_gender_city, x_train_cough],
    axis=1
)

x_test_transformer = np.concatenate(
    [x_test_age, x_test_fever, x_test_gender_city, x_test_cough],
    axis=1
)

x_train_transformer.shape

(80, 7)

In [35]:
x_test_transformer.shape

(20, 7)

If You Know , How to use Column Transformer , So we Use this

In [38]:
from sklearn.compose import ColumnTransformer

In [45]:
transformer = ColumnTransformer(
    transformers=[
        ('t1', SimpleImputer(), ['fever']),
        ('t2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),
        ('t3', OneHotEncoder(drop='first', sparse_output=False), ['gender', 'city'])
    ],
    remainder='passthrough'
)

In [47]:
transformer.fit_transform(x_train)

array([[ 99.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  65.        ],
       [101.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  64.        ],
       [101.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  68.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  17.        ],
       [ 98.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  80.        ],
       [100.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  19.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  56.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  12.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  27.        ],
       [100.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  27.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  38.        ],
       [103.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  60.        ],
       [103.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  83.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  49.        ],
       [102.        ,   1.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  20.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  25.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  16.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  16.        ],
       [ 99.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  59.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  25.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  75.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  12.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  13.        ],
       [102.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  49.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  18.        ],
       [103.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  46.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  44.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  55.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  60.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  31.        ],
       [101.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  49.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  19.        ],
       [102.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  24.        ],
       [103.        ,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  70.        ],
       [102.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  69.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  11.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  51.        ],
       [101.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  14.        ],
       [103.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  73.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  34.        ],
       [102.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  33.        ],
       [100.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  27.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   5.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  48.        ],
       [101.02739726,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  38.        ],
       [101.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  42.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  22.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  81.        ],
       [101.02739726,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  42.        ],
       [101.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  19.        ],
       [101.02739726,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  75.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  54.        ],
       [ 98.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  83.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  51.        ],
       [101.02739726,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  82.        ],
       [101.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  34.        ],
       [ 99.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  72.        ],
       [102.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  82.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  74.        ],
       [101.02739726,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  20.        ],
       [101.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  15.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   8.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  26.        ],
       [101.02739726,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  34.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   6.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  64.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  80.        ],
       [ 98.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  24.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  42.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  65.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  71.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   5.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  64.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  65.        ],
       [ 98.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  73.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  11.        ],
       [100.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   5.        ],
       [102.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  82.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  34.        ],
       [101.02739726,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  71.        ]])

In [48]:
transformer.fit_transform(x_train).shape

(80, 7)

In [49]:
transformer.transform(x_test).shape

(20, 7)