In [19]:
import pandas as pd
import requests

In [20]:
#Paste the you API Key in {API_KEY} so the code will working
response = requests.get(
    'https://api.themoviedb.org/3/tv/top_rated?api_key={API_KEY}&language=en-US&page=1'
)

In [21]:
response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/wh5agdl3b7fqC7mSjsCkHx4fMAs.jpg',
   'genre_ids': [37, 18],
   'id': 299167,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Dutton Ranch',
   'overview': 'Rip Wheeler and Beth Dutton gamble everything on a new life in South Texas, but the promise of building a future far from the ghosts of Yellowstone quickly collides with brutal new realities and a rival ranch that will stop at nothing to protect its empire.',
   'popularity': 143.0673,
   'poster_path': '/xsiecCxd8lkcAluw0wWwbW5CwSv.jpg',
   'first_air_date': '2026-05-15',
   'softcore': False,
   'name': 'Dutton Ranch',
   'vote_average': 9.3,
   'vote_count': 237},
  {'adult': False,
   'backdrop_path': '/52sp0vPhLOWrZ1QoZIWiapronM.jpg',
   'genre_ids': [18],
   'id': 273240,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Off Campus',
   'overview': 'Hannah Wells tutors hockey captain Garrett Graham to win over her crush. Their deal becomes real connection as they face their pasts. Friends Logan, Dean, Tucker, and Allie navigate college life and love.',
   'popularity': 508.6964,
   'poster_path': '/cbODFqkcmRgrYH8NkG4Q4Hcg8Z1.jpg',
   'first_air_date': '2026-05-13',
   'softcore': False,
   'name': 'Off Campus',
   'vote_average': 9.0,
   'vote_count': 422},
  {'adult': False,
   'backdrop_path': '/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
   'genre_ids': [18, 80],
   'id': 1396,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Breaking Bad',
   'overview': "Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
   'popularity': 171.472,
   'poster_path': '/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg',
   'first_air_date': '2008-01-20',
   'softcore': False,
   'name': 'Breaking Bad',
   'vote_average': 8.946,
   'vote_count': 17895},
  {'adult': False,
   'backdrop_path': '/rBOnrVlck7BIlGeWVlzYiZeg4l2.jpg',
   'genre_ids': [16, 10759, 18, 10765],
   'id': 209867,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': '葬送のフリーレン',
   'overview': 'After the party of heroes defeated the Demon King, they restored peace to the land and returned to lives of solitude.  Generations pass, and the elven mage Frieren comes face to face with humanity’s mortality. She takes on a new apprentice and promises to fulfill old friends’ dying wishes. Can an elven mind make peace with the nature of life and death? Frieren embarks on her quest to find out.',
   'popularity': 64.5506,
   'poster_path': '/dqZENchTd7lp5zht7BdlqM7RBhD.jpg',
   'first_air_date': '2023-09-29',
   'softcore': False,
   'name': "Frieren: Beyond Journey's End",
   'vote_average': 8.806,
   'vote_count': 844},
  {'adult': False,
   'backdrop_path': '/sZH7lGs06skRKkrqp1LRi57VVMb.jpg',
   'genre_ids': [35],
   'id': 64010,
   'origin_country': ['KR'],
   'original_language': 'ko',
   'original_name': '응답하라 1988',
   'overview': 'Take a nostalgic trip back to the late 1980s through the lives of five families and their five teenage kids living in a small neighbourhood in Seoul.',
   'popularity': 16.9599,
   'poster_path': '/i3xQJlQRff4k5IMEY55l4iKaKl3.jpg',
   'first_air_date': '2015-11-06',
   'softcore': False,
   'name': 'Reply 1988',
   'vote_average': 8.8,
   'vote_count': 213},
  {'adult': False,
   'backdrop_path': '/7oBGhqJIghRBvOwo5Qe0yM0cnMc.jpg',
   'genre_ids': [16, 10759, 10765],
   'id': 246,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Avatar: The Last Airbender',
   'overview': 'In a war-torn world of elemental magic, a young boy reawakens to undertake a dangerous mystic quest to fulfill his destiny as the Avatar, and bring peace to the world.',
   'popularity': 23.314,
   'poster_path': '/9RQhVb3r3mCMqYVhLoCu4EvuipP.jpg',
   'first_air_date': '2005-02-21',
   'softcore': False,
   'name': 'Avatar: The Last Airbender',
   'vote_average': 8.762,
   'vote_count': 4865},
  {'adult': False,
   'backdrop_path': '/q8eejQcg1bAqImEV8jh8RtBD4uH.jpg',
   'genre_ids': [16, 10759, 10765],
   'id': 94605,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Arcane',
   'overview': 'Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.',
   'popularity': 31.6236,
   'poster_path': '/abf8tHznhSvl9BAElD2cQeRr7do.jpg',
   'first_air_date': '2021-11-06',
   'softcore': False,
   'name': 'Arcane',
   'vote_average': 8.752,
   'vote_count': 5925},
  {'adult': False,
   'backdrop_path': '/7Sgo1XdCrIpJpiNsTPMi9vwKSuC.jpg',
   'genre_ids': [18],
   'id': 250307,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'The Pitt',
   'overview': "The staff of Pittsburgh's Trauma Medical Center work around the clock to save lives in an overcrowded and underfunded emergency department.",
   'popularity': 56.9368,
   'poster_path': '/kvFSpESyBZMjaeOJDx7RS3P1jey.jpg',
   'first_air_date': '2025-01-09',
   'softcore': False,
   'name': 'The Pitt',
   'vote_average': 8.743,
   'vote_count': 774},
  {'adult': False,
   'backdrop_path': '/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg',
   'genre_ids': [10759, 35, 16],
   'id': 37854,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': 'ワンピース',
   'overview': 'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
   'popularity': 61.4081,
   'poster_path': '/dB4EDhre2dsC2kxYDavyKWqLQwi.jpg',
   'first_air_date': '1999-10-20',
   'softcore': False,
   'name': 'One Piece',
   'vote_average': 8.738,
   'vote_count': 5339},
  {'adult': False,
   'backdrop_path': '/mwczMJeoQrsPERcyP1e900jo3Jv.jpg',
   'genre_ids': [18],
   'id': 219246,
   'origin_country': ['KR'],
   'original_language': 'ko',
   'original_name': '폭싹 속았수다',
   'overview': "In Jeju, a spirited girl and a steadfast boy's island story blossoms into a lifelong tale of setbacks and triumphs — proving love endures across time.",
   'popularity': 29.7204,
   'poster_path': '/1VC3sEFxYXYDqQUCAnvWfUsYg1s.jpg',
   'first_air_date': '2025-03-07',
   'softcore': False,
   'name': 'When Life Gives You Tangerines',
   'vote_average': 8.735,
   'vote_count': 532},
  {'adult': False,
   'backdrop_path': '/3siv3RaQrdr2tQiv9jHq71sLlzo.jpg',
   'genre_ids': [10759, 10751, 18],
   'id': 85077,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'The Chosen',
   'overview': 'The life of Christ through the eyes of those who encountered him.',
   'popularity': 43.3018,
   'poster_path': '/dqVUFuNrMFWt7uGNWlpo91VKYOI.jpg',
   'first_air_date': '2019-04-21',
   'softcore': False,
   'name': 'The Chosen',
   'vote_average': 8.731,
   'vote_count': 889},
  {'adult': False,
   'backdrop_path': '/QbRbCULZVBcrN2uydpmIOQLV5O.jpg',
   'genre_ids': [18],
   'id': 301507,
   'origin_country': ['CA'],
   'original_language': 'en',
   'original_name': 'Heated Rivalry',
   'overview': 'Two of the biggest stars in Major League Hockey are bound by ambition, rivalry, and a magnetic pull neither of them fully understands. What begins as a secret fling between two fresh faced rookies evolves into a years-long journey of love, denial, and self-discovery. Over the next eight years, as they chase glory on the ice, they struggle to navigate their feelings for each other. Torn between the sport they live for and the love they can’t ignore, they must decide if there’s room in their fiercely competitive world for something as fragile – and powerful – as real love.',
   'popularity': 24.1945,
   'poster_path': '/3YCKbtAkYWCMDLHvkUjGhG7eWoS.jpg',
   'first_air_date': '2025-11-28',
   'softcore': False,
   'name': 'Heated Rivalry',
   'vote_average': 8.724,
   'vote_count': 502},
  {'adult': False,
   'backdrop_path': '/3URK0z9PzpVNJrGE7XOuyy6KFzk.jpg',
   'genre_ids': [18],
   'id': 87108,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Chernobyl',
   'overview': 'The true story of one of the worst man-made catastrophes in history: the catastrophic nuclear accident at Chernobyl. A tale of the brave men and women who sacrificed to save Europe from unimaginable disaster.',
   'popularity': 22.7825,
   'poster_path': '/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg',
   'first_air_date': '2019-05-06',
   'softcore': False,
   'name': 'Chernobyl',
   'vote_average': 8.713,
   'vote_count': 7918},
  {'adult': False,
   'backdrop_path': '/2UG177tWHy7xRmMKWJHB7nAUmKd.jpg',
   'genre_ids': [16, 10759, 10765, 18],
   'id': 31911,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': '鋼の錬金術師 FULLMETAL ALCHEMIST',
   'overview': 'Disregard for alchemy’s laws ripped half of Edward Elric’s limbs from his body and left his brother Alphonse’s soul clinging to a suit of armor. To restore what was lost, the brothers seek the Philosopher’s Stone. Enemies and allies – the corrupt military, the Homunculi, and foreign alchemists – will alter the Elric brothers course, but their purpose will remain unchanged and their bond unbreakable.',
   'popularity': 47.6992,
   'poster_path': '/5ZFUEOULaVml7pQuXxhpR2SmVUw.jpg',
   'first_air_date': '2009-04-05',
   'softcore': False,
   'name': 'Fullmetal Alchemist: Brotherhood',
   'vote_average': 8.711,
   'vote_count': 2463},
  {'adult': False,
   'backdrop_path': '/dl3pdT1NZiqRM4aDBwsD2TtO8x9.jpg',
   'genre_ids': [16, 18],
   'id': 271607,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': '薫る花は凛と咲く',
   'overview': 'When the intimidating Rintaro meets the open-minded Kaoruko, the unlikely duo grows closer. The issue? Their neighboring high schools hate each other.',
   'popularity': 22.9678,
   'poster_path': '/g1sYAQt0OeCxzyfagSEqxUlsLnt.jpg',
   'first_air_date': '2025-07-06',
   'softcore': False,
   'name': 'The Fragrant Flower Blooms with Dignity',
   'vote_average': 8.678,
   'vote_count': 216},
  {'adult': False,
   'backdrop_path': '/og2jKploGHYnCz68vV1nRSEE0xV.jpg',
   'genre_ids': [80, 18],
   'id': 60059,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Better Call Saul',
   'overview': 'Six years before Saul Goodman meets Walter White. We meet him when the man who will become Saul Goodman is known as Jimmy McGill, a small-time lawyer searching for his destiny, and, more immediately, hustling to make ends meet. Working alongside, and, often, against Jimmy, is “fixer” Mike Ehrmantraut. The series tracks Jimmy’s transformation into Saul Goodman, the man who puts “criminal” in “criminal lawyer".',
   'popularity': 92.3785,
   'poster_path': '/zjg4jpK1Wp2kiRvtt5ND0kznako.jpg',
   'first_air_date': '2015-02-08',
   'softcore': False,
   'name': 'Better Call Saul',
   'vote_average': 8.706,
   'vote_count': 6522},
  {'adult': False,
   'backdrop_path': '/hj2YSkoqHB2FPHeoALfdd4eufue.jpg',
   'genre_ids': [10759, 18],
   'id': 200709,
   'origin_country': ['KR'],
   'original_language': 'ko',
   'original_name': '약한영웅',
   'overview': 'With the aid of unexpected friends, a gifted but introverted student confronts bullies and violent foes — unaware of how dangerous his world will become.',
   'popularity': 71.2243,
   'poster_path': '/dbqNBeLvAWFqpAvdBc0cecaqytT.jpg',
   'first_air_date': '2022-11-18',
   'softcore': False,
   'name': 'Weak Hero',
   'vote_average': 8.683,
   'vote_count': 447},
  {'adult': False,
   'backdrop_path': '/rqbCbjB19amtOtFQbb3K2lgm2zv.jpg',
   'genre_ids': [16, 10765, 10759],
   'id': 1429,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': '進撃の巨人',
   'overview': '100 years ago, the last remnants of humanity were forced to retreat behind the towering walls of a fortified city to escape the massive, man-eating Titans that roamed the land outside their fortress. Only the members of the Scouting Legion dared to stray beyond the safety of the walls – but even those brave warriors seldom returned alive. Those within the city clung to the illusion of a peaceful existence until the day that dream was shattered, and their slim chance at survival was reduced to one horrifying choice: kill – or be devoured!',
   'popularity': 39.7976,
   'poster_path': '/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg',
   'first_air_date': '2013-04-07',
   'softcore': False,
   'name': 'Attack on Titan',
   'vote_average': 8.68,
   'vote_count': 7440},
  {'adult': False,
   'backdrop_path': '/9In9QgVJx7PlFOAgVHCKKSbo605.jpg',
   'genre_ids': [16, 35, 10765, 10759],
   'id': 60625,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Rick and Morty',
   'overview': 'Follows a sociopathic genius scientist who drags his inherently timid grandson on adventures across the universe.',
   'popularity': 178.1888,
   'poster_path': '/owhkU6KRqdXoUQpjV8uyZGPtX58.jpg',
   'first_air_date': '2013-12-02',
   'softcore': False,
   'name': 'Rick and Morty',
   'vote_average': 8.678,
   'vote_count': 10953},
  {'adult': False,
   'backdrop_path': '/lNpkvX2s8LGB0mjGODMT4o6Up7j.jpg',
   'genre_ids': [80, 18],
   'id': 1398,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'The Sopranos',
   'overview': "The story of New Jersey-based Italian-American mobster Tony Soprano and the difficulties he faces as he tries to balance the conflicting requirements of his home life and the criminal organization he heads. Those difficulties are often highlighted through his ongoing professional relationship with psychiatrist Jennifer Melfi. The show features Tony's family members and Mafia associates in prominent roles and story arcs, most notably his wife Carmela and his cousin and protégé Christopher Moltisanti.",
   'popularity': 94.422,
   'poster_path': '/rTc7ZXdroqjkKivFPvCPX0Ru7uw.jpg',
   'first_air_date': '1999-01-10',
   'softcore': False,
   'name': 'The Sopranos',
   'vote_average': 8.672,
   'vote_count': 3479}],
 'total_pages': 123,
 'total_results': 2457}

In [22]:
#trying to fetch a specific data

response.json()['results']

[{'adult': False,
  'backdrop_path': '/wh5agdl3b7fqC7mSjsCkHx4fMAs.jpg',
  'genre_ids': [37, 18],
  'id': 299167,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Dutton Ranch',
  'overview': 'Rip Wheeler and Beth Dutton gamble everything on a new life in South Texas, but the promise of building a future far from the ghosts of Yellowstone quickly collides with brutal new realities and a rival ranch that will stop at nothing to protect its empire.',
  'popularity': 143.0673,
  'poster_path': '/xsiecCxd8lkcAluw0wWwbW5CwSv.jpg',
  'first_air_date': '2026-05-15',
  'softcore': False,
  'name': 'Dutton Ranch',
  'vote_average': 9.3,
  'vote_count': 237},
 {'adult': False,
  'backdrop_path': '/52sp0vPhLOWrZ1QoZIWiapronM.jpg',
  'genre_ids': [18],
  'id': 273240,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Off Campus',
  'overview': 'Hannah Wells tutors hockey captain Garrett Graham to win over her crush. Their deal becomes real connection as they face their pasts. Friends Logan, Dean, Tucker, and Allie navigate college life and love.',
  'popularity': 508.6964,
  'poster_path': '/cbODFqkcmRgrYH8NkG4Q4Hcg8Z1.jpg',
  'first_air_date': '2026-05-13',
  'softcore': False,
  'name': 'Off Campus',
  'vote_average': 9.0,
  'vote_count': 422},
 {'adult': False,
  'backdrop_path': '/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
  'genre_ids': [18, 80],
  'id': 1396,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Breaking Bad',
  'overview': "Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
  'popularity': 171.472,
  'poster_path': '/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg',
  'first_air_date': '2008-01-20',
  'softcore': False,
  'name': 'Breaking Bad',
  'vote_average': 8.946,
  'vote_count': 17895},
 {'adult': False,
  'backdrop_path': '/rBOnrVlck7BIlGeWVlzYiZeg4l2.jpg',
  'genre_ids': [16, 10759, 18, 10765],
  'id': 209867,
  'origin_country': ['JP'],
  'original_language': 'ja',
  'original_name': '葬送のフリーレン',
  'overview': 'After the party of heroes defeated the Demon King, they restored peace to the land and returned to lives of solitude.  Generations pass, and the elven mage Frieren comes face to face with humanity’s mortality. She takes on a new apprentice and promises to fulfill old friends’ dying wishes. Can an elven mind make peace with the nature of life and death? Frieren embarks on her quest to find out.',
  'popularity': 64.5506,
  'poster_path': '/dqZENchTd7lp5zht7BdlqM7RBhD.jpg',
  'first_air_date': '2023-09-29',
  'softcore': False,
  'name': "Frieren: Beyond Journey's End",
  'vote_average': 8.806,
  'vote_count': 844},
 {'adult': False,
  'backdrop_path': '/sZH7lGs06skRKkrqp1LRi57VVMb.jpg',
  'genre_ids': [35],
  'id': 64010,
  'origin_country': ['KR'],
  'original_language': 'ko',
  'original_name': '응답하라 1988',
  'overview': 'Take a nostalgic trip back to the late 1980s through the lives of five families and their five teenage kids living in a small neighbourhood in Seoul.',
  'popularity': 16.9599,
  'poster_path': '/i3xQJlQRff4k5IMEY55l4iKaKl3.jpg',
  'first_air_date': '2015-11-06',
  'softcore': False,
  'name': 'Reply 1988',
  'vote_average': 8.8,
  'vote_count': 213},
 {'adult': False,
  'backdrop_path': '/7oBGhqJIghRBvOwo5Qe0yM0cnMc.jpg',
  'genre_ids': [16, 10759, 10765],
  'id': 246,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Avatar: The Last Airbender',
  'overview': 'In a war-torn world of elemental magic, a young boy reawakens to undertake a dangerous mystic quest to fulfill his destiny as the Avatar, and bring peace to the world.',
  'popularity': 23.314,
  'poster_path': '/9RQhVb3r3mCMqYVhLoCu4EvuipP.jpg',
  'first_air_date': '2005-02-21',
  'softcore': False,
  'name': 'Avatar: The Last Airbender',
  'vote_average': 8.762,
  'vote_count': 4865},
 {'adult': False,
  'backdrop_path': '/q8eejQcg1bAqImEV8jh8RtBD4uH.jpg',
  'genre_ids': [16, 10759, 10765],
  'id': 94605,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Arcane',
  'overview': 'Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.',
  'popularity': 31.6236,
  'poster_path': '/abf8tHznhSvl9BAElD2cQeRr7do.jpg',
  'first_air_date': '2021-11-06',
  'softcore': False,
  'name': 'Arcane',
  'vote_average': 8.752,
  'vote_count': 5925},
 {'adult': False,
  'backdrop_path': '/7Sgo1XdCrIpJpiNsTPMi9vwKSuC.jpg',
  'genre_ids': [18],
  'id': 250307,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'The Pitt',
  'overview': "The staff of Pittsburgh's Trauma Medical Center work around the clock to save lives in an overcrowded and underfunded emergency department.",
  'popularity': 56.9368,
  'poster_path': '/kvFSpESyBZMjaeOJDx7RS3P1jey.jpg',
  'first_air_date': '2025-01-09',
  'softcore': False,
  'name': 'The Pitt',
  'vote_average': 8.743,
  'vote_count': 774},
 {'adult': False,
  'backdrop_path': '/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg',
  'genre_ids': [10759, 35, 16],
  'id': 37854,
  'origin_country': ['JP'],
  'original_language': 'ja',
  'original_name': 'ワンピース',
  'overview': 'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
  'popularity': 61.4081,
  'poster_path': '/dB4EDhre2dsC2kxYDavyKWqLQwi.jpg',
  'first_air_date': '1999-10-20',
  'softcore': False,
  'name': 'One Piece',
  'vote_average': 8.738,
  'vote_count': 5339},
 {'adult': False,
  'backdrop_path': '/mwczMJeoQrsPERcyP1e900jo3Jv.jpg',
  'genre_ids': [18],
  'id': 219246,
  'origin_country': ['KR'],
  'original_language': 'ko',
  'original_name': '폭싹 속았수다',
  'overview': "In Jeju, a spirited girl and a steadfast boy's island story blossoms into a lifelong tale of setbacks and triumphs — proving love endures across time.",
  'popularity': 29.7204,
  'poster_path': '/1VC3sEFxYXYDqQUCAnvWfUsYg1s.jpg',
  'first_air_date': '2025-03-07',
  'softcore': False,
  'name': 'When Life Gives You Tangerines',
  'vote_average': 8.735,
  'vote_count': 532},
 {'adult': False,
  'backdrop_path': '/3siv3RaQrdr2tQiv9jHq71sLlzo.jpg',
  'genre_ids': [10759, 10751, 18],
  'id': 85077,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'The Chosen',
  'overview': 'The life of Christ through the eyes of those who encountered him.',
  'popularity': 43.3018,
  'poster_path': '/dqVUFuNrMFWt7uGNWlpo91VKYOI.jpg',
  'first_air_date': '2019-04-21',
  'softcore': False,
  'name': 'The Chosen',
  'vote_average': 8.731,
  'vote_count': 889},
 {'adult': False,
  'backdrop_path': '/QbRbCULZVBcrN2uydpmIOQLV5O.jpg',
  'genre_ids': [18],
  'id': 301507,
  'origin_country': ['CA'],
  'original_language': 'en',
  'original_name': 'Heated Rivalry',
  'overview': 'Two of the biggest stars in Major League Hockey are bound by ambition, rivalry, and a magnetic pull neither of them fully understands. What begins as a secret fling between two fresh faced rookies evolves into a years-long journey of love, denial, and self-discovery. Over the next eight years, as they chase glory on the ice, they struggle to navigate their feelings for each other. Torn between the sport they live for and the love they can’t ignore, they must decide if there’s room in their fiercely competitive world for something as fragile – and powerful – as real love.',
  'popularity': 24.1945,
  'poster_path': '/3YCKbtAkYWCMDLHvkUjGhG7eWoS.jpg',
  'first_air_date': '2025-11-28',
  'softcore': False,
  'name': 'Heated Rivalry',
  'vote_average': 8.724,
  'vote_count': 502},
 {'adult': False,
  'backdrop_path': '/3URK0z9PzpVNJrGE7XOuyy6KFzk.jpg',
  'genre_ids': [18],
  'id': 87108,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Chernobyl',
  'overview': 'The true story of one of the worst man-made catastrophes in history: the catastrophic nuclear accident at Chernobyl. A tale of the brave men and women who sacrificed to save Europe from unimaginable disaster.',
  'popularity': 22.7825,
  'poster_path': '/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg',
  'first_air_date': '2019-05-06',
  'softcore': False,
  'name': 'Chernobyl',
  'vote_average': 8.713,
  'vote_count': 7918},
 {'adult': False,
  'backdrop_path': '/2UG177tWHy7xRmMKWJHB7nAUmKd.jpg',
  'genre_ids': [16, 10759, 10765, 18],
  'id': 31911,
  'origin_country': ['JP'],
  'original_language': 'ja',
  'original_name': '鋼の錬金術師 FULLMETAL ALCHEMIST',
  'overview': 'Disregard for alchemy’s laws ripped half of Edward Elric’s limbs from his body and left his brother Alphonse’s soul clinging to a suit of armor. To restore what was lost, the brothers seek the Philosopher’s Stone. Enemies and allies – the corrupt military, the Homunculi, and foreign alchemists – will alter the Elric brothers course, but their purpose will remain unchanged and their bond unbreakable.',
  'popularity': 47.6992,
  'poster_path': '/5ZFUEOULaVml7pQuXxhpR2SmVUw.jpg',
  'first_air_date': '2009-04-05',
  'softcore': False,
  'name': 'Fullmetal Alchemist: Brotherhood',
  'vote_average': 8.711,
  'vote_count': 2463},
 {'adult': False,
  'backdrop_path': '/dl3pdT1NZiqRM4aDBwsD2TtO8x9.jpg',
  'genre_ids': [16, 18],
  'id': 271607,
  'origin_country': ['JP'],
  'original_language': 'ja',
  'original_name': '薫る花は凛と咲く',
  'overview': 'When the intimidating Rintaro meets the open-minded Kaoruko, the unlikely duo grows closer. The issue? Their neighboring high schools hate each other.',
  'popularity': 22.9678,
  'poster_path': '/g1sYAQt0OeCxzyfagSEqxUlsLnt.jpg',
  'first_air_date': '2025-07-06',
  'softcore': False,
  'name': 'The Fragrant Flower Blooms with Dignity',
  'vote_average': 8.678,
  'vote_count': 216},
 {'adult': False,
  'backdrop_path': '/og2jKploGHYnCz68vV1nRSEE0xV.jpg',
  'genre_ids': [80, 18],
  'id': 60059,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Better Call Saul',
  'overview': 'Six years before Saul Goodman meets Walter White. We meet him when the man who will become Saul Goodman is known as Jimmy McGill, a small-time lawyer searching for his destiny, and, more immediately, hustling to make ends meet. Working alongside, and, often, against Jimmy, is “fixer” Mike Ehrmantraut. The series tracks Jimmy’s transformation into Saul Goodman, the man who puts “criminal” in “criminal lawyer".',
  'popularity': 92.3785,
  'poster_path': '/zjg4jpK1Wp2kiRvtt5ND0kznako.jpg',
  'first_air_date': '2015-02-08',
  'softcore': False,
  'name': 'Better Call Saul',
  'vote_average': 8.706,
  'vote_count': 6522},
 {'adult': False,
  'backdrop_path': '/hj2YSkoqHB2FPHeoALfdd4eufue.jpg',
  'genre_ids': [10759, 18],
  'id': 200709,
  'origin_country': ['KR'],
  'original_language': 'ko',
  'original_name': '약한영웅',
  'overview': 'With the aid of unexpected friends, a gifted but introverted student confronts bullies and violent foes — unaware of how dangerous his world will become.',
  'popularity': 71.2243,
  'poster_path': '/dbqNBeLvAWFqpAvdBc0cecaqytT.jpg',
  'first_air_date': '2022-11-18',
  'softcore': False,
  'name': 'Weak Hero',
  'vote_average': 8.683,
  'vote_count': 447},
 {'adult': False,
  'backdrop_path': '/rqbCbjB19amtOtFQbb3K2lgm2zv.jpg',
  'genre_ids': [16, 10765, 10759],
  'id': 1429,
  'origin_country': ['JP'],
  'original_language': 'ja',
  'original_name': '進撃の巨人',
  'overview': '100 years ago, the last remnants of humanity were forced to retreat behind the towering walls of a fortified city to escape the massive, man-eating Titans that roamed the land outside their fortress. Only the members of the Scouting Legion dared to stray beyond the safety of the walls – but even those brave warriors seldom returned alive. Those within the city clung to the illusion of a peaceful existence until the day that dream was shattered, and their slim chance at survival was reduced to one horrifying choice: kill – or be devoured!',
  'popularity': 39.7976,
  'poster_path': '/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg',
  'first_air_date': '2013-04-07',
  'softcore': False,
  'name': 'Attack on Titan',
  'vote_average': 8.68,
  'vote_count': 7440},
 {'adult': False,
  'backdrop_path': '/9In9QgVJx7PlFOAgVHCKKSbo605.jpg',
  'genre_ids': [16, 35, 10765, 10759],
  'id': 60625,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Rick and Morty',
  'overview': 'Follows a sociopathic genius scientist who drags his inherently timid grandson on adventures across the universe.',
  'popularity': 178.1888,
  'poster_path': '/owhkU6KRqdXoUQpjV8uyZGPtX58.jpg',
  'first_air_date': '2013-12-02',
  'softcore': False,
  'name': 'Rick and Morty',
  'vote_average': 8.678,
  'vote_count': 10953},
 {'adult': False,
  'backdrop_path': '/lNpkvX2s8LGB0mjGODMT4o6Up7j.jpg',
  'genre_ids': [80, 18],
  'id': 1398,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'The Sopranos',
  'overview': "The story of New Jersey-based Italian-American mobster Tony Soprano and the difficulties he faces as he tries to balance the conflicting requirements of his home life and the criminal organization he heads. Those difficulties are often highlighted through his ongoing professional relationship with psychiatrist Jennifer Melfi. The show features Tony's family members and Mafia associates in prominent roles and story arcs, most notably his wife Carmela and his cousin and protégé Christopher Moltisanti.",
  'popularity': 94.422,
  'poster_path': '/rTc7ZXdroqjkKivFPvCPX0Ru7uw.jpg',
  'first_air_date': '1999-01-10',
  'softcore': False,
  'name': 'The Sopranos',
  'vote_average': 8.672,
  'vote_count': 3479}]

In [23]:
#converted list into datafram

pd.DataFrame(response.json()['results'])

,adult,backdrop_path,genre_ids,id,origin_country,original_language,original_name,overview,popularity,poster_path,first_air_date,softcore,name,vote_average,vote_count
0,False,/wh5agdl3b7fqC7mSjsCkHx4fMAs.jpg,"[37, 18]",299167,[US],en,Dutton Ranch,Rip Wheeler and Beth Dutton gamble everything ...,143.0673,/xsiecCxd8lkcAluw0wWwbW5CwSv.jpg,2026-05-15,False,Dutton Ranch,9.300,237
1,False,/52sp0vPhLOWrZ1QoZIWiapronM.jpg,[18],273240,[US],en,Off Campus,Hannah Wells tutors hockey captain Garrett Gra...,508.6964,/cbODFqkcmRgrYH8NkG4Q4Hcg8Z1.jpg,2026-05-13,False,Off Campus,9.000,422
2,False,/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg,"[18, 80]",1396,[US],en,Breaking Bad,"Walter White, a New Mexico chemistry teacher, ...",171.4720,/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg,2008-01-20,False,Breaking Bad,8.946,17895
3,False,/rBOnrVlck7BIlGeWVlzYiZeg4l2.jpg,"[16, 10759, 18, 10765]",209867,[JP],ja,葬送のフリーレン,After the party of heroes defeated the Demon K...,64.5506,/dqZENchTd7lp5zht7BdlqM7RBhD.jpg,2023-09-29,False,Frieren: Beyond Journey's End,8.806,844
4,False,/sZH7lGs06skRKkrqp1LRi57VVMb.jpg,[35],64010,[KR],ko,응답하라 1988,Take a nostalgic trip back to the late 1980s t...,16.9599,/i3xQJlQRff4k5IMEY55l4iKaKl3.jpg,2015-11-06,False,Reply 1988,8.800,213
5,False,/7oBGhqJIghRBvOwo5Qe0yM0cnMc.jpg,"[16, 10759, 10765]",246,[US],en,Avatar: The Last Airbender,"In a war-torn world of elemental magic, a youn...",23.3140,/9RQhVb3r3mCMqYVhLoCu4EvuipP.jpg,2005-02-21,False,Avatar: The Last Airbender,8.762,4865
6,False,/q8eejQcg1bAqImEV8jh8RtBD4uH.jpg,"[16, 10759, 10765]",94605,[US],en,Arcane,Amid the stark discord of twin cities Piltover...,31.6236,/abf8tHznhSvl9BAElD2cQeRr7do.jpg,2021-11-06,False,Arcane,8.752,5925
7,False,/7Sgo1XdCrIpJpiNsTPMi9vwKSuC.jpg,[18],250307,[US],en,The Pitt,The staff of Pittsburgh's Trauma Medical Cente...,56.9368,/kvFSpESyBZMjaeOJDx7RS3P1jey.jpg,2025-01-09,False,The Pitt,8.743,774
8,False,/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg,"[10759, 35, 16]",37854,[JP],ja,ワンピース,"Years ago, the fearsome Pirate King, Gol D. Ro...",61.4081,/dB4EDhre2dsC2kxYDavyKWqLQwi.jpg,1999-10-20,False,One Piece,8.738,5339
9,False,/mwczMJeoQrsPERcyP1e900jo3Jv.jpg,[18],219246,[KR],ko,폭싹 속았수다,"In Jeju, a spirited girl and a steadfast boy's...",29.7204,/1VC3sEFxYXYDqQUCAnvWfUsYg1s.jpg,2025-03-07,False,When Life Gives You Tangerines,8.735,532
10,False,/3siv3RaQrdr2tQiv9jHq71sLlzo.jpg,"[10759, 10751, 18]",85077,[US],en,The Chosen,The life of Christ through the eyes of those w...,43.3018,/dqVUFuNrMFWt7uGNWlpo91VKYOI.jpg,2019-04-21,False,The Chosen,8.731,889
11,False,/QbRbCULZVBcrN2uydpmIOQLV5O.jpg,[18],301507,[CA],en,Heated Rivalry,Two of the biggest stars in Major League Hocke...,24.1945,/3YCKbtAkYWCMDLHvkUjGhG7eWoS.jpg,2025-11-28,False,Heated Rivalry,8.724,502
12,False,/3URK0z9PzpVNJrGE7XOuyy6KFzk.jpg,[18],87108,[US],en,Chernobyl,The true story of one of the worst man-made ca...,22.7825,/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg,2019-05-06,False,Chernobyl,8.713,7918
13,False,/2UG177tWHy7xRmMKWJHB7nAUmKd.jpg,"[16, 10759, 10765, 18]",31911,[JP],ja,鋼の錬金術師 FULLMETAL ALCHEMIST,Disregard for alchemy’s laws ripped half of Ed...,47.6992,/5ZFUEOULaVml7pQuXxhpR2SmVUw.jpg,2009-04-05,False,Fullmetal Alchemist: Brotherhood,8.711,2463
14,False,/dl3pdT1NZiqRM4aDBwsD2TtO8x9.jpg,"[16, 18]",271607,[JP],ja,薫る花は凛と咲く,When the intimidating Rintaro meets the open-m...,22.9678,/g1sYAQt0OeCxzyfagSEqxUlsLnt.jpg,2025-07-06,False,The Fragrant Flower Blooms with Dignity,8.678,216
15,False,/og2jKploGHYnCz68vV1nRSEE0xV.jpg,"[80, 18]",60059,[US],en,Better Call Saul,Six years before Saul Goodman meets Walter Whi...,92.3785,/zjg4jpK1Wp2kiRvtt5ND0kznako.jpg,2015-02-08,False,Better Call Saul,8.706,6522
16,False,/hj2YSkoqHB2FPHeoALfdd4eufue.jpg,"[10759, 18]",200709,[KR],ko,약한영웅,"With the aid of unexpected friends, a gifted b...",71.2243,/dbqNBeLvAWFqpAvdBc0cecaqytT.jpg,2022-11-18,False,Weak Hero,8.683,447
17,False,/rqbCbjB19amtOtFQbb3K2lgm2zv.jpg,"[16, 10765, 10759]",1429,[JP],ja,進撃の巨人,"100 years ago, the last remnants of humanity w...",39.7976,/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg,2013-04-07,False,Attack on Titan,8.680,7440
18,False,/9In9QgVJx7PlFOAgVHCKKSbo605.jpg,"[16, 35, 10765, 10759]",60625,[US],en,Rick and Morty,Follows a sociopathic genius scientist who dra...,178.1888,/owhkU6KRqdXoUQpjV8uyZGPtX58.jpg,2013-12-02,False,Rick and Morty,8.678,10953
19,False,/lNpkvX2s8LGB0mjGODMT4o6Up7j.jpg,"[80, 18]",1398,[US],en,The Sopranos,The story of New Jersey-based Italian-American...,94.4220,/rTc7ZXdroqjkKivFPvCPX0Ru7uw.jpg,1999-01-10,False,The Sopranos,8.672,3479

In [24]:
temp_df =pd.DataFrame(response.json()['results']).head(2)

In [25]:
#fetchind specific data which we wanted
df = pd.DataFrame(response.json()['results'])[
    ['id','original_name','overview','original_name',
     'popularity','vote_average','vote_count']]

In [26]:
df.head()

,id,original_name,overview,original_name,popularity,vote_average,vote_count
0,299167,Dutton Ranch,Rip Wheeler and Beth Dutton gamble everything ...,Dutton Ranch,143.0673,9.300,237
1,273240,Off Campus,Hannah Wells tutors hockey captain Garrett Gra...,Off Campus,508.6964,9.000,422
2,1396,Breaking Bad,"Walter White, a New Mexico chemistry teacher, ...",Breaking Bad,171.4720,8.946,17895
3,209867,葬送のフリーレン,After the party of heroes defeated the Demon K...,葬送のフリーレン,64.5506,8.806,844
4,64010,응답하라 1988,Take a nostalgic trip back to the late 1980s t...,응답하라 1988,16.9599,8.800,213

In [27]:
df = pd.DataFrame()

In [28]:
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
for i in range(1,124):
    response = requests.get(
        'https://api.themoviedb.org/3/tv/top_rated?api_key={API_KEY}&language=en-US&page=1'.format(i)
    )

    temp_df = pd.DataFrame(response.json()['results'])[
        ['id','original_name','overview','original_name',
         'popularity','vote_average','vote_count']
    ]

    df = pd.concat([df, temp_df], ignore_index=True)

In [ ]:
df

In [ ]:
df.to_csv('movie.csv')