Working with CSV Files

In [1]:
#import pandas
import pandas as pd

In [2]:
#Opening a CSV file from an URL
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {"User-Agent": "Mozilla/5.0(Macintosh; Intel Mac Os x 10:14; rv:66:0) Gecko/20100101 Firfox/66.0"} 
req = requests.get(url,headers=headers)
data= StringIO(req.text)

pd.read_csv(data)

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

In [3]:
#sep Parameter
pd.read_csv("https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv", sep="\t")

              Country,Region
0             Algeria,AFRICA
1              Angola,AFRICA
2               Benin,AFRICA
3            Botswana,AFRICA
4             Burkina,AFRICA
..                       ...
189   Paraguay,SOUTH AMERICA
190       Peru,SOUTH AMERICA
191   Suriname,SOUTH AMERICA
192    Uruguay,SOUTH AMERICA
193  Venezuela,SOUTH AMERICA

[194 rows x 1 columns]

In [4]:
#if Parameters do not have name or name is removed
df = pd.read_csv("https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv", names=['Country' , 'Region'] )

In [5]:
df.head()

    Country  Region
0   Country  Region
1   Algeria  AFRICA
2    Angola  AFRICA
3     Benin  AFRICA
4  Botswana  AFRICA

In [6]:
#Shapes
df.shape

(195, 2)

In [7]:
#Colums
df.columns

Index(['Country', 'Region'], dtype='object')

In [8]:
#for info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  195 non-null    object
 1   Region   195 non-null    object
dtypes: object(2)
memory usage: 3.2+ KB

In [9]:
#header parameter
pd.read_csv("https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv", header=1)

       Algeria         AFRICA
0       Angola         AFRICA
1        Benin         AFRICA
2     Botswana         AFRICA
3      Burkina         AFRICA
4      Burundi         AFRICA
..         ...            ...
188   Paraguay  SOUTH AMERICA
189       Peru  SOUTH AMERICA
190   Suriname  SOUTH AMERICA
191    Uruguay  SOUTH AMERICA
192  Venezuela  SOUTH AMERICA

[193 rows x 2 columns]

In [10]:
#use_cols Parameters
pd.read_csv("https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv", usecols=['Country' , 'Region'])

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

In [11]:
#Squeeze parameters
import pandas as pd
# Read the CSV and convert to Series using .squeeze() method instead of squeeze parameter
df = pd.read_csv("https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv", usecols=['Region']).squeeze()

# Alternative approach: Access the column directly to get a Series
# df = pd.read_csv("https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv", usecols=['Region'])['Region']

In [14]:
#skiprows parameters
df = pd.read_csv(
    "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv",
    skiprows=1
)

In [15]:
#Econding Parameter
df = pd.read_csv("https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv",encoding='latin-1')

In [16]:
#Skip  bad Lines
df = pd.read_csv("https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv",encoding='latin-1', on_bad_lines='skip')

In [ ]:
#dtypes parameter
df = pd.read_csv(
    "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv",
    dtype={'Region':int}).info()

In [ ]:
#Handling Dates
df = pd.read_csv(
    "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv",
    parse_dates=['date']).info()

In [19]:
#convertors
def rename(name):
    if name == "AFRICA":
        return "Africa"
    else:
        return name

In [20]:
rename("AFRICA")

'Africa'

In [21]:
df = pd.read_csv("https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv", converters= {'Region': rename})

In [22]:
#na_values parameters
pd.read_csv("https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv",na_values=["Botswana"])

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3          NaN         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

In [23]:
#Loading a hug dataset in chunks
dfs = pd.read_csv("https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv", chunksize=50)

In [24]:
for chunks in dfs:
    print(chunks.shape)

(50, 2)
(50, 2)
(50, 2)
(44, 2)

This is Some important commands for CSV not a complete Project. SO some of the command are not working in this datasets.